// <auto-generated />
namespace testWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NewFieldsOnContact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFieldsOnContact));
        
        string IMigrationMetadata.Id
        {
            get { return "201409101535164_NewFieldsOnContact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
